spring:
  application:
    name: Huiban-BackEnd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huiban?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: root
    # druid-spring-boot-starter 依赖自动生效 druid，可以不配置 type 属性，但建议配置
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/static/
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    enabled: true
    encoding: UTF-8
    mode: HTML

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 5s
      timeout: 5s

      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  config-location: classpath:mybatis-config.xml
  # 实体类的位置
  type-aliases-package: com.example.huibanbackend.entity

